### ISSUE TITLE
background color bug? 

### ISSUE THREAD

**Issue by ghost** [timdubbins/tap#1] opened 2023-05-22 14:44 UTC
i love this project, ive been looking for a rust music player for ages, but when i compile and run it, the background color is this salmon-like color, not the black like in the screenshot, all the other colors of the text are the same, i dont know if its because i compiled it wrong, i just used cargo build

**Comment by timdubbins** [comment] 2023-05-22 21:49
Hi, thanks for the report!

Can I ask what terminal you are using? Some terminals do not support true color (I'm using Alacritty, which is the terminal used to take the screenshots). 

The background color is set in `src/assets/style.toml` and if you change the file so that it reads: 
``` toml
shadow  = false
borders = "simple"

[colors]
	background = ["#1d1f21", "black"]
	view       = ["#1d1f21", "black"]
```

then you should get a black background regardless of the terminal you are using (if the terminal doesn't support true color it will fall back to using the default black).

Hope this helps

**Comment by ghost** [comment] 2023-05-23 00:47
im using alacritty too, i think its a problem with my system because i couldnt find any reference to a color similar to the one i was getting in the source

**Comment by timdubbins** [comment] 2023-07-01 11:23
Did you manage to resolve the color issue?

**Comment by timdubbins** [comment] 2023-09-24 11:35
I'll close this because I can't reproduce it

**Closed as not planned** 2023-09-24 11:35 UTC
